# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  host: localhost
development:
  <<: *default
  database: task_management_app_development

test:
  <<: *default
  database: task_management_app_test

production:
  <<: *default
  database: task_management_app_production
  username: task_management_app
  password: <%= ENV['TASK_MANAGEMENT_APP_DATABASE_PASSWORD'] %>
